name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Confirma se a tua branch principal se chama 'main' ou 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependências
        run: npm install

      # Aqui ele cria o ficheiro .env com as chaves que vamos configurar no passo 3
      - name: Criar arquivo .env
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

      - name: Build do Projeto
        run: npm run build

      - name: Upload dos arquivos do site (Artifact)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Importante: No teu vite.config.ts tu definiste 'build' e não 'dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4